//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bazaF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RPPP10 : DbContext
    {
        public RPPP10()
            : base("name=RPPP10")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Branitelj> Branitelj { get; set; }
        public virtual DbSet<FizickaOsoba> FizickaOsoba { get; set; }
        public virtual DbSet<KategorijaSuda> KategorijaSuda { get; set; }
        public virtual DbSet<Kazna> Kazna { get; set; }
        public virtual DbSet<Mjesto> Mjesto { get; set; }
        public virtual DbSet<Optuzba> Optuzba { get; set; }
        public virtual DbSet<Optuzenik> Optuzenik { get; set; }
        public virtual DbSet<Osoba> Osoba { get; set; }
        public virtual DbSet<Ostecenik> Ostecenik { get; set; }
        public virtual DbSet<PravnaOsoba> PravnaOsoba { get; set; }
        public virtual DbSet<Presuda> Presuda { get; set; }
        public virtual DbSet<Proces> Proces { get; set; }
        public virtual DbSet<RazinaZakona> RazinaZakona { get; set; }
        public virtual DbSet<Rociste> Rociste { get; set; }
        public virtual DbSet<StavkaSpisa> StavkaSpisa { get; set; }
        public virtual DbSet<Sud> Sud { get; set; }
        public virtual DbSet<Sudac> Sudac { get; set; }
        public virtual DbSet<Sudionik> Sudionik { get; set; }
        public virtual DbSet<SudskoVijece> SudskoVijece { get; set; }
        public virtual DbSet<Svjedok> Svjedok { get; set; }
        public virtual DbSet<TekstOptuzbe> TekstOptuzbe { get; set; }
        public virtual DbSet<TipPresude> TipPresude { get; set; }
        public virtual DbSet<Tuzitelj> Tuzitelj { get; set; }
        public virtual DbSet<UlogaSudionika> UlogaSudionika { get; set; }
        public virtual DbSet<VrstaKazne> VrstaKazne { get; set; }
        public virtual DbSet<VrstaOznake> VrstaOznake { get; set; }
        public virtual DbSet<VrstaSpisa> VrstaSpisa { get; set; }
        public virtual DbSet<Zakon> Zakon { get; set; }
    }
}
