//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System.ComponentModel;

namespace bazaF
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    
    public partial class FizickaOsoba
    {
        public string ImePrezime
        {
            get
            {
                return this.Ime + " " + this.Prezime;
            }

        }
        
        public FizickaOsoba()
        {
            this.Branitelj = new BindingList<Branitelj>();
            this.Sudionik = new BindingList<Sudionik>();
            this.Svjedok = new BindingList<Svjedok>();
            this.Tuzitelj = new BindingList<Tuzitelj>();
        }
    
        public int IDOsobe { get; set; }
        public string Ime { get; set; }
        public string Prezime { get; set; }
        public string ImeOca { get; set; }
        public Nullable<System.DateTime> DatumRod { get; set; }
        public string JMBG { get; set; }
        public Nullable<int> Poslodavac { get; set; }
        public Nullable<bool> Odvjetnik { get; set; }
        public Nullable<bool> Sudac { get; set; }
    
        public virtual BindingList<Branitelj> Branitelj { get; set; }
        public virtual Osoba Osoba { get; set; }
        public virtual PravnaOsoba PravnaOsoba { get; set; }
        public virtual ICollection<Sudionik> Sudionik { get; set; }
        public virtual ICollection<Svjedok> Svjedok { get; set; }
        public virtual ICollection<Tuzitelj> Tuzitelj { get; set; }
    }
}
