//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel;

namespace bazaF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Osoba
    {
        public Osoba()
        {
            this.Kazna = new BindingList<Kazna>();
            this.Optuzenik = new BindingList<Optuzenik>();
            this.Ostecenik = new BindingList<Ostecenik>();
        }
    
        public int IDOsobe { get; set; }
        public string OIB { get; set; }
        public string UlicaIKucniBr { get; set; }
        public Nullable<int> PBr { get; set; }
    
        public virtual FizickaOsoba FizickaOsoba { get; set; }
        public virtual ICollection<Kazna> Kazna { get; set; }
        public virtual Mjesto Mjesto { get; set; }
        public virtual BindingList<Optuzenik> Optuzenik { get; set; }
        public virtual BindingList<Ostecenik> Ostecenik { get; set; }
        public virtual PravnaOsoba PravnaOsoba { get; set; }
        public virtual Sudac Sudac { get; set; }
    }
}
