//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bazaF
{
    using System;
    using System.Collections.Generic;
    
    public partial class RazinaZakona
    {
        public RazinaZakona()
        {
            this.Zakon = new HashSet<Zakon>();
        }
    
        public int SifraRazine { get; set; }
        public string NazivRazine { get; set; }
    
        public virtual ICollection<Zakon> Zakon { get; set; }
    }
}
