//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bazaF
{
    using System;
    using System.Collections.Generic;
    
    public partial class StavkaSpisa
    {
        public int IDStavke { get; set; }
        public string NazivStavke { get; set; }
        public Nullable<int> VrstaSpisa { get; set; }
        public Nullable<int> IDProcesa { get; set; }
        public Nullable<System.DateTime> DatumUnosa { get; set; }
        public byte[] Dokument { get; set; }
    
        public virtual Proces Proces { get; set; }
        public virtual VrstaSpisa VrstaSpisa1 { get; set; }
    }
}
