//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System.ComponentModel;

namespace bazaF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sudac
    {
        public Sudac()
        {
            this.SudskoVijece = new BindingList<SudskoVijece>();
        }
    
        public int IDOsobe { get; set; }
        public int IDSuda { get; set; }
    
        public virtual Osoba Osoba { get; set; }
        public virtual Sud Sud { get; set; }
        public virtual BindingList<SudskoVijece> SudskoVijece { get; set; }
    }
}
