//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bazaF
{
    using System;
    using System.Collections.Generic;
    
    public partial class TekstOptuzbe
    {
        public int IDOptuzbe { get; set; }
        public string Tekst { get; set; }
        public int IDOptuzenika { get; set; }
        public int IDProcesa { get; set; }
    
        public virtual Optuzenik Optuzenik { get; set; }
        public virtual Proces Proces { get; set; }
    }
}
