//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bazaF
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    
    public partial class UlogaSudionika
    {
        public UlogaSudionika()
        {
            this.Sudionik = new BindingList<Sudionik>();
        }
    
        public int SifraUloge { get; set; }
        public string NazivUloge { get; set; }
    
        public virtual BindingList<Sudionik> Sudionik { get; set; }
    }
}
