//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bazaF
{
    using System;
    using System.Collections.Generic;
    
    public partial class VrstaSpisa
    {
        public VrstaSpisa()
        {
            this.StavkaSpisa = new HashSet<StavkaSpisa>();
        }
    
        public int SifraVrste { get; set; }
        public string NazivVrste { get; set; }
    
        public virtual ICollection<StavkaSpisa> StavkaSpisa { get; set; }
    }
}
