//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManuelaKajkara.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Sud", Namespace="http://schemas.datacontract.org/2004/07/UgovoriKlase")]
    [System.SerializableAttribute()]
    public partial class Sud : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AdresaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NazivField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PBrField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int kategorijaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Adresa {
            get {
                return this.AdresaField;
            }
            set {
                if ((object.ReferenceEquals(this.AdresaField, value) != true)) {
                    this.AdresaField = value;
                    this.RaisePropertyChanged("Adresa");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Naziv {
            get {
                return this.NazivField;
            }
            set {
                if ((object.ReferenceEquals(this.NazivField, value) != true)) {
                    this.NazivField = value;
                    this.RaisePropertyChanged("Naziv");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PBr {
            get {
                return this.PBrField;
            }
            set {
                if ((this.PBrField.Equals(value) != true)) {
                    this.PBrField = value;
                    this.RaisePropertyChanged("PBr");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int kategorija {
            get {
                return this.kategorijaField;
            }
            set {
                if ((this.kategorijaField.Equals(value) != true)) {
                    this.kategorijaField = value;
                    this.RaisePropertyChanged("kategorija");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Kategorija", Namespace="http://schemas.datacontract.org/2004/07/UgovoriKlase")]
    [System.SerializableAttribute()]
    public partial class Kategorija : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nazivField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string naziv {
            get {
                return this.nazivField;
            }
            set {
                if ((object.ReferenceEquals(this.nazivField, value) != true)) {
                    this.nazivField = value;
                    this.RaisePropertyChanged("naziv");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Mjesto", Namespace="http://schemas.datacontract.org/2004/07/UgovoriKlase")]
    [System.SerializableAttribute()]
    public partial class Mjesto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nazivField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int pbrField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string naziv {
            get {
                return this.nazivField;
            }
            set {
                if ((object.ReferenceEquals(this.nazivField, value) != true)) {
                    this.nazivField = value;
                    this.RaisePropertyChanged("naziv");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int pbr {
            get {
                return this.pbrField;
            }
            set {
                if ((this.pbrField.Equals(value) != true)) {
                    this.pbrField = value;
                    this.RaisePropertyChanged("pbr");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FizOsoba", Namespace="http://schemas.datacontract.org/2004/07/ManuelaKajkara")]
    [System.SerializableAttribute()]
    public partial class FizOsoba : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AdresaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DatumField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDOsobeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ImeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ImeOcaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string JMBGField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MjestoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OIBField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool OdvjetnikField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PoslodavacField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PrezimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool SudacField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Adresa {
            get {
                return this.AdresaField;
            }
            set {
                if ((object.ReferenceEquals(this.AdresaField, value) != true)) {
                    this.AdresaField = value;
                    this.RaisePropertyChanged("Adresa");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Datum {
            get {
                return this.DatumField;
            }
            set {
                if ((this.DatumField.Equals(value) != true)) {
                    this.DatumField = value;
                    this.RaisePropertyChanged("Datum");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IDOsobe {
            get {
                return this.IDOsobeField;
            }
            set {
                if ((this.IDOsobeField.Equals(value) != true)) {
                    this.IDOsobeField = value;
                    this.RaisePropertyChanged("IDOsobe");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Ime {
            get {
                return this.ImeField;
            }
            set {
                if ((object.ReferenceEquals(this.ImeField, value) != true)) {
                    this.ImeField = value;
                    this.RaisePropertyChanged("Ime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ImeOca {
            get {
                return this.ImeOcaField;
            }
            set {
                if ((object.ReferenceEquals(this.ImeOcaField, value) != true)) {
                    this.ImeOcaField = value;
                    this.RaisePropertyChanged("ImeOca");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string JMBG {
            get {
                return this.JMBGField;
            }
            set {
                if ((object.ReferenceEquals(this.JMBGField, value) != true)) {
                    this.JMBGField = value;
                    this.RaisePropertyChanged("JMBG");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mjesto {
            get {
                return this.MjestoField;
            }
            set {
                if ((object.ReferenceEquals(this.MjestoField, value) != true)) {
                    this.MjestoField = value;
                    this.RaisePropertyChanged("Mjesto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OIB {
            get {
                return this.OIBField;
            }
            set {
                if ((object.ReferenceEquals(this.OIBField, value) != true)) {
                    this.OIBField = value;
                    this.RaisePropertyChanged("OIB");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Odvjetnik {
            get {
                return this.OdvjetnikField;
            }
            set {
                if ((this.OdvjetnikField.Equals(value) != true)) {
                    this.OdvjetnikField = value;
                    this.RaisePropertyChanged("Odvjetnik");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Poslodavac {
            get {
                return this.PoslodavacField;
            }
            set {
                if ((this.PoslodavacField.Equals(value) != true)) {
                    this.PoslodavacField = value;
                    this.RaisePropertyChanged("Poslodavac");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Prezime {
            get {
                return this.PrezimeField;
            }
            set {
                if ((object.ReferenceEquals(this.PrezimeField, value) != true)) {
                    this.PrezimeField = value;
                    this.RaisePropertyChanged("Prezime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Sudac {
            get {
                return this.SudacField;
            }
            set {
                if ((this.SudacField.Equals(value) != true)) {
                    this.SudacField = value;
                    this.RaisePropertyChanged("Sudac");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Kazna", Namespace="http://schemas.datacontract.org/2004/07/ManuelaKajkara")]
    [System.SerializableAttribute()]
    public partial class Kazna : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDKazneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDOsobeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> IDPresudeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal IznosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NazivField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OpisField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ManuelaKajkara.ServiceReference1.FizickaOsoba OsobaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PresudaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int VrstaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IDKazne {
            get {
                return this.IDKazneField;
            }
            set {
                if ((this.IDKazneField.Equals(value) != true)) {
                    this.IDKazneField = value;
                    this.RaisePropertyChanged("IDKazne");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IDOsobe {
            get {
                return this.IDOsobeField;
            }
            set {
                if ((this.IDOsobeField.Equals(value) != true)) {
                    this.IDOsobeField = value;
                    this.RaisePropertyChanged("IDOsobe");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> IDPresude {
            get {
                return this.IDPresudeField;
            }
            set {
                if ((this.IDPresudeField.Equals(value) != true)) {
                    this.IDPresudeField = value;
                    this.RaisePropertyChanged("IDPresude");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Iznos {
            get {
                return this.IznosField;
            }
            set {
                if ((this.IznosField.Equals(value) != true)) {
                    this.IznosField = value;
                    this.RaisePropertyChanged("Iznos");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Naziv {
            get {
                return this.NazivField;
            }
            set {
                if ((object.ReferenceEquals(this.NazivField, value) != true)) {
                    this.NazivField = value;
                    this.RaisePropertyChanged("Naziv");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Opis {
            get {
                return this.OpisField;
            }
            set {
                if ((object.ReferenceEquals(this.OpisField, value) != true)) {
                    this.OpisField = value;
                    this.RaisePropertyChanged("Opis");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ManuelaKajkara.ServiceReference1.FizickaOsoba Osoba {
            get {
                return this.OsobaField;
            }
            set {
                if ((object.ReferenceEquals(this.OsobaField, value) != true)) {
                    this.OsobaField = value;
                    this.RaisePropertyChanged("Osoba");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Presuda {
            get {
                return this.PresudaField;
            }
            set {
                if ((object.ReferenceEquals(this.PresudaField, value) != true)) {
                    this.PresudaField = value;
                    this.RaisePropertyChanged("Presuda");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Vrsta {
            get {
                return this.VrstaField;
            }
            set {
                if ((this.VrstaField.Equals(value) != true)) {
                    this.VrstaField = value;
                    this.RaisePropertyChanged("Vrsta");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FizickaOsoba", Namespace="http://schemas.datacontract.org/2004/07/ManuelaKajkara")]
    [System.SerializableAttribute()]
    public partial class FizickaOsoba : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AdresaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DatumRodField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDOsobeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ImeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ImeOcaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ImePrezimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string JMBGField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PrezimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int pbrField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ulicaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Adresa {
            get {
                return this.AdresaField;
            }
            set {
                if ((object.ReferenceEquals(this.AdresaField, value) != true)) {
                    this.AdresaField = value;
                    this.RaisePropertyChanged("Adresa");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DatumRod {
            get {
                return this.DatumRodField;
            }
            set {
                if ((this.DatumRodField.Equals(value) != true)) {
                    this.DatumRodField = value;
                    this.RaisePropertyChanged("DatumRod");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IDOsobe {
            get {
                return this.IDOsobeField;
            }
            set {
                if ((this.IDOsobeField.Equals(value) != true)) {
                    this.IDOsobeField = value;
                    this.RaisePropertyChanged("IDOsobe");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Ime {
            get {
                return this.ImeField;
            }
            set {
                if ((object.ReferenceEquals(this.ImeField, value) != true)) {
                    this.ImeField = value;
                    this.RaisePropertyChanged("Ime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ImeOca {
            get {
                return this.ImeOcaField;
            }
            set {
                if ((object.ReferenceEquals(this.ImeOcaField, value) != true)) {
                    this.ImeOcaField = value;
                    this.RaisePropertyChanged("ImeOca");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ImePrezime {
            get {
                return this.ImePrezimeField;
            }
            set {
                if ((object.ReferenceEquals(this.ImePrezimeField, value) != true)) {
                    this.ImePrezimeField = value;
                    this.RaisePropertyChanged("ImePrezime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string JMBG {
            get {
                return this.JMBGField;
            }
            set {
                if ((object.ReferenceEquals(this.JMBGField, value) != true)) {
                    this.JMBGField = value;
                    this.RaisePropertyChanged("JMBG");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Prezime {
            get {
                return this.PrezimeField;
            }
            set {
                if ((object.ReferenceEquals(this.PrezimeField, value) != true)) {
                    this.PrezimeField = value;
                    this.RaisePropertyChanged("Prezime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int pbr {
            get {
                return this.pbrField;
            }
            set {
                if ((this.pbrField.Equals(value) != true)) {
                    this.pbrField = value;
                    this.RaisePropertyChanged("pbr");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ulica {
            get {
                return this.ulicaField;
            }
            set {
                if ((object.ReferenceEquals(this.ulicaField, value) != true)) {
                    this.ulicaField = value;
                    this.RaisePropertyChanged("ulica");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IFirmaServis")]
    public interface IFirmaServis {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFirmaServis/PopisSudova", ReplyAction="http://tempuri.org/IFirmaServis/PopisSudovaResponse")]
        ManuelaKajkara.ServiceReference1.Sud[] PopisSudova();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFirmaServis/PopisSudova", ReplyAction="http://tempuri.org/IFirmaServis/PopisSudovaResponse")]
        System.Threading.Tasks.Task<ManuelaKajkara.ServiceReference1.Sud[]> PopisSudovaAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFirmaServis/DohvatiJedan", ReplyAction="http://tempuri.org/IFirmaServis/DohvatiJedanResponse")]
        ManuelaKajkara.ServiceReference1.Sud DohvatiJedan(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFirmaServis/DohvatiJedan", ReplyAction="http://tempuri.org/IFirmaServis/DohvatiJedanResponse")]
        System.Threading.Tasks.Task<ManuelaKajkara.ServiceReference1.Sud> DohvatiJedanAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFirmaServis/PopisKategorija", ReplyAction="http://tempuri.org/IFirmaServis/PopisKategorijaResponse")]
        ManuelaKajkara.ServiceReference1.Kategorija[] PopisKategorija();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFirmaServis/PopisKategorija", ReplyAction="http://tempuri.org/IFirmaServis/PopisKategorijaResponse")]
        System.Threading.Tasks.Task<ManuelaKajkara.ServiceReference1.Kategorija[]> PopisKategorijaAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFirmaServis/PopisMjesta", ReplyAction="http://tempuri.org/IFirmaServis/PopisMjestaResponse")]
        ManuelaKajkara.ServiceReference1.Mjesto[] PopisMjesta();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFirmaServis/PopisMjesta", ReplyAction="http://tempuri.org/IFirmaServis/PopisMjestaResponse")]
        System.Threading.Tasks.Task<ManuelaKajkara.ServiceReference1.Mjesto[]> PopisMjestaAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFirmaServis/ObrisiSud", ReplyAction="http://tempuri.org/IFirmaServis/ObrisiSudResponse")]
        void ObrisiSud(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFirmaServis/ObrisiSud", ReplyAction="http://tempuri.org/IFirmaServis/ObrisiSudResponse")]
        System.Threading.Tasks.Task ObrisiSudAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFirmaServis/DodajNoviSud", ReplyAction="http://tempuri.org/IFirmaServis/DodajNoviSudResponse")]
        void DodajNoviSud(int id, string naziv, string adresa, int pbr, int kategorija);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFirmaServis/DodajNoviSud", ReplyAction="http://tempuri.org/IFirmaServis/DodajNoviSudResponse")]
        System.Threading.Tasks.Task DodajNoviSudAsync(int id, string naziv, string adresa, int pbr, int kategorija);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFirmaServis/UrediSud", ReplyAction="http://tempuri.org/IFirmaServis/UrediSudResponse")]
        void UrediSud(int id, string naziv, string adresa, int pbr, int kategorija);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFirmaServis/UrediSud", ReplyAction="http://tempuri.org/IFirmaServis/UrediSudResponse")]
        System.Threading.Tasks.Task UrediSudAsync(int id, string naziv, string adresa, int pbr, int kategorija);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFirmaServis/DajSveFizickeOsobe", ReplyAction="http://tempuri.org/IFirmaServis/DajSveFizickeOsobeResponse")]
        ManuelaKajkara.ServiceReference1.FizOsoba[] DajSveFizickeOsobe();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFirmaServis/DajSveFizickeOsobe", ReplyAction="http://tempuri.org/IFirmaServis/DajSveFizickeOsobeResponse")]
        System.Threading.Tasks.Task<ManuelaKajkara.ServiceReference1.FizOsoba[]> DajSveFizickeOsobeAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFirmaServis/DajFizickuOsobu", ReplyAction="http://tempuri.org/IFirmaServis/DajFizickuOsobuResponse")]
        ManuelaKajkara.ServiceReference1.FizOsoba DajFizickuOsobu(int ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFirmaServis/DajFizickuOsobu", ReplyAction="http://tempuri.org/IFirmaServis/DajFizickuOsobuResponse")]
        System.Threading.Tasks.Task<ManuelaKajkara.ServiceReference1.FizOsoba> DajFizickuOsobuAsync(int ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFirmaServis/UnesiFizickuOsobu", ReplyAction="http://tempuri.org/IFirmaServis/UnesiFizickuOsobuResponse")]
        void UnesiFizickuOsobu(ManuelaKajkara.ServiceReference1.FizOsoba osoba);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFirmaServis/UnesiFizickuOsobu", ReplyAction="http://tempuri.org/IFirmaServis/UnesiFizickuOsobuResponse")]
        System.Threading.Tasks.Task UnesiFizickuOsobuAsync(ManuelaKajkara.ServiceReference1.FizOsoba osoba);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFirmaServis/PromijeniFizickuOsobu", ReplyAction="http://tempuri.org/IFirmaServis/PromijeniFizickuOsobuResponse")]
        void PromijeniFizickuOsobu(ManuelaKajkara.ServiceReference1.FizOsoba osoba);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFirmaServis/PromijeniFizickuOsobu", ReplyAction="http://tempuri.org/IFirmaServis/PromijeniFizickuOsobuResponse")]
        System.Threading.Tasks.Task PromijeniFizickuOsobuAsync(ManuelaKajkara.ServiceReference1.FizOsoba osoba);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFirmaServis/ObrisiFizickuOsobu", ReplyAction="http://tempuri.org/IFirmaServis/ObrisiFizickuOsobuResponse")]
        void ObrisiFizickuOsobu(int ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFirmaServis/ObrisiFizickuOsobu", ReplyAction="http://tempuri.org/IFirmaServis/ObrisiFizickuOsobuResponse")]
        System.Threading.Tasks.Task ObrisiFizickuOsobuAsync(int ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFirmaServis/DajSveKazne", ReplyAction="http://tempuri.org/IFirmaServis/DajSveKazneResponse")]
        ManuelaKajkara.ServiceReference1.Kazna[] DajSveKazne();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFirmaServis/DajSveKazne", ReplyAction="http://tempuri.org/IFirmaServis/DajSveKazneResponse")]
        System.Threading.Tasks.Task<ManuelaKajkara.ServiceReference1.Kazna[]> DajSveKazneAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFirmaServis/DajKaznu", ReplyAction="http://tempuri.org/IFirmaServis/DajKaznuResponse")]
        ManuelaKajkara.ServiceReference1.Kazna DajKaznu(int ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFirmaServis/DajKaznu", ReplyAction="http://tempuri.org/IFirmaServis/DajKaznuResponse")]
        System.Threading.Tasks.Task<ManuelaKajkara.ServiceReference1.Kazna> DajKaznuAsync(int ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFirmaServis/UnesiKaznu", ReplyAction="http://tempuri.org/IFirmaServis/UnesiKaznuResponse")]
        void UnesiKaznu(ManuelaKajkara.ServiceReference1.Kazna kazna);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFirmaServis/UnesiKaznu", ReplyAction="http://tempuri.org/IFirmaServis/UnesiKaznuResponse")]
        System.Threading.Tasks.Task UnesiKaznuAsync(ManuelaKajkara.ServiceReference1.Kazna kazna);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFirmaServis/PromijeniKaznu", ReplyAction="http://tempuri.org/IFirmaServis/PromijeniKaznuResponse")]
        void PromijeniKaznu(ManuelaKajkara.ServiceReference1.Kazna kazna);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFirmaServis/PromijeniKaznu", ReplyAction="http://tempuri.org/IFirmaServis/PromijeniKaznuResponse")]
        System.Threading.Tasks.Task PromijeniKaznuAsync(ManuelaKajkara.ServiceReference1.Kazna kazna);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFirmaServis/ObrisiKaznu", ReplyAction="http://tempuri.org/IFirmaServis/ObrisiKaznuResponse")]
        void ObrisiKaznu(int ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFirmaServis/ObrisiKaznu", ReplyAction="http://tempuri.org/IFirmaServis/ObrisiKaznuResponse")]
        System.Threading.Tasks.Task ObrisiKaznuAsync(int ID);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IFirmaServisChannel : ManuelaKajkara.ServiceReference1.IFirmaServis, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FirmaServisClient : System.ServiceModel.ClientBase<ManuelaKajkara.ServiceReference1.IFirmaServis>, ManuelaKajkara.ServiceReference1.IFirmaServis {
        
        public FirmaServisClient() {
        }
        
        public FirmaServisClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public FirmaServisClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FirmaServisClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FirmaServisClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public ManuelaKajkara.ServiceReference1.Sud[] PopisSudova() {
            return base.Channel.PopisSudova();
        }
        
        public System.Threading.Tasks.Task<ManuelaKajkara.ServiceReference1.Sud[]> PopisSudovaAsync() {
            return base.Channel.PopisSudovaAsync();
        }
        
        public ManuelaKajkara.ServiceReference1.Sud DohvatiJedan(int id) {
            return base.Channel.DohvatiJedan(id);
        }
        
        public System.Threading.Tasks.Task<ManuelaKajkara.ServiceReference1.Sud> DohvatiJedanAsync(int id) {
            return base.Channel.DohvatiJedanAsync(id);
        }
        
        public ManuelaKajkara.ServiceReference1.Kategorija[] PopisKategorija() {
            return base.Channel.PopisKategorija();
        }
        
        public System.Threading.Tasks.Task<ManuelaKajkara.ServiceReference1.Kategorija[]> PopisKategorijaAsync() {
            return base.Channel.PopisKategorijaAsync();
        }
        
        public ManuelaKajkara.ServiceReference1.Mjesto[] PopisMjesta() {
            return base.Channel.PopisMjesta();
        }
        
        public System.Threading.Tasks.Task<ManuelaKajkara.ServiceReference1.Mjesto[]> PopisMjestaAsync() {
            return base.Channel.PopisMjestaAsync();
        }
        
        public void ObrisiSud(int id) {
            base.Channel.ObrisiSud(id);
        }
        
        public System.Threading.Tasks.Task ObrisiSudAsync(int id) {
            return base.Channel.ObrisiSudAsync(id);
        }
        
        public void DodajNoviSud(int id, string naziv, string adresa, int pbr, int kategorija) {
            base.Channel.DodajNoviSud(id, naziv, adresa, pbr, kategorija);
        }
        
        public System.Threading.Tasks.Task DodajNoviSudAsync(int id, string naziv, string adresa, int pbr, int kategorija) {
            return base.Channel.DodajNoviSudAsync(id, naziv, adresa, pbr, kategorija);
        }
        
        public void UrediSud(int id, string naziv, string adresa, int pbr, int kategorija) {
            base.Channel.UrediSud(id, naziv, adresa, pbr, kategorija);
        }
        
        public System.Threading.Tasks.Task UrediSudAsync(int id, string naziv, string adresa, int pbr, int kategorija) {
            return base.Channel.UrediSudAsync(id, naziv, adresa, pbr, kategorija);
        }
        
        public ManuelaKajkara.ServiceReference1.FizOsoba[] DajSveFizickeOsobe() {
            return base.Channel.DajSveFizickeOsobe();
        }
        
        public System.Threading.Tasks.Task<ManuelaKajkara.ServiceReference1.FizOsoba[]> DajSveFizickeOsobeAsync() {
            return base.Channel.DajSveFizickeOsobeAsync();
        }
        
        public ManuelaKajkara.ServiceReference1.FizOsoba DajFizickuOsobu(int ID) {
            return base.Channel.DajFizickuOsobu(ID);
        }
        
        public System.Threading.Tasks.Task<ManuelaKajkara.ServiceReference1.FizOsoba> DajFizickuOsobuAsync(int ID) {
            return base.Channel.DajFizickuOsobuAsync(ID);
        }
        
        public void UnesiFizickuOsobu(ManuelaKajkara.ServiceReference1.FizOsoba osoba) {
            base.Channel.UnesiFizickuOsobu(osoba);
        }
        
        public System.Threading.Tasks.Task UnesiFizickuOsobuAsync(ManuelaKajkara.ServiceReference1.FizOsoba osoba) {
            return base.Channel.UnesiFizickuOsobuAsync(osoba);
        }
        
        public void PromijeniFizickuOsobu(ManuelaKajkara.ServiceReference1.FizOsoba osoba) {
            base.Channel.PromijeniFizickuOsobu(osoba);
        }
        
        public System.Threading.Tasks.Task PromijeniFizickuOsobuAsync(ManuelaKajkara.ServiceReference1.FizOsoba osoba) {
            return base.Channel.PromijeniFizickuOsobuAsync(osoba);
        }
        
        public void ObrisiFizickuOsobu(int ID) {
            base.Channel.ObrisiFizickuOsobu(ID);
        }
        
        public System.Threading.Tasks.Task ObrisiFizickuOsobuAsync(int ID) {
            return base.Channel.ObrisiFizickuOsobuAsync(ID);
        }
        
        public ManuelaKajkara.ServiceReference1.Kazna[] DajSveKazne() {
            return base.Channel.DajSveKazne();
        }
        
        public System.Threading.Tasks.Task<ManuelaKajkara.ServiceReference1.Kazna[]> DajSveKazneAsync() {
            return base.Channel.DajSveKazneAsync();
        }
        
        public ManuelaKajkara.ServiceReference1.Kazna DajKaznu(int ID) {
            return base.Channel.DajKaznu(ID);
        }
        
        public System.Threading.Tasks.Task<ManuelaKajkara.ServiceReference1.Kazna> DajKaznuAsync(int ID) {
            return base.Channel.DajKaznuAsync(ID);
        }
        
        public void UnesiKaznu(ManuelaKajkara.ServiceReference1.Kazna kazna) {
            base.Channel.UnesiKaznu(kazna);
        }
        
        public System.Threading.Tasks.Task UnesiKaznuAsync(ManuelaKajkara.ServiceReference1.Kazna kazna) {
            return base.Channel.UnesiKaznuAsync(kazna);
        }
        
        public void PromijeniKaznu(ManuelaKajkara.ServiceReference1.Kazna kazna) {
            base.Channel.PromijeniKaznu(kazna);
        }
        
        public System.Threading.Tasks.Task PromijeniKaznuAsync(ManuelaKajkara.ServiceReference1.Kazna kazna) {
            return base.Channel.PromijeniKaznuAsync(kazna);
        }
        
        public void ObrisiKaznu(int ID) {
            base.Channel.ObrisiKaznu(ID);
        }
        
        public System.Threading.Tasks.Task ObrisiKaznuAsync(int ID) {
            return base.Channel.ObrisiKaznuAsync(ID);
        }
    }
}
