//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RPPP
{
    using System;
    using System.Collections.Generic;
    
    public partial class FizickaOsoba
    {
        public FizickaOsoba()
        {
            this.Branitelj = new HashSet<Branitelj>();
            this.SudskoVijece = new HashSet<SudskoVijece>();
            this.Svjedok = new HashSet<Svjedok>();
            this.Tuzitelj = new HashSet<Tuzitelj>();
        }
    
        public int IDOsobe { get; set; }
        public string Ime { get; set; }
        public string Prezime { get; set; }
        public string ImeOca { get; set; }
        public Nullable<System.DateTime> DatumRod { get; set; }
        public string JMBG { get; set; }
        public Nullable<int> Poslodavac { get; set; }
    
        public virtual ICollection<Branitelj> Branitelj { get; set; }
        public virtual Osoba Osoba { get; set; }
        public virtual PravnaOsoba PravnaOsoba { get; set; }
        public virtual ICollection<SudskoVijece> SudskoVijece { get; set; }
        public virtual ICollection<Svjedok> Svjedok { get; set; }
        public virtual ICollection<Tuzitelj> Tuzitelj { get; set; }
    }
}
