//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RPPP
{
    using System;
    using System.Collections.Generic;
    
    public partial class KategorijaSuda
    {
        public KategorijaSuda()
        {
            this.Sud = new HashSet<Sud>();
        }
    
        public int SifraKatSuda { get; set; }
        public string NazivKatSuda { get; set; }
    
        public virtual ICollection<Sud> Sud { get; set; }
    }
}
