//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RPPP
{
    using System;
    using System.Collections.Generic;
    
    public partial class Osoba
    {
        public Osoba()
        {
            this.Kazna = new HashSet<Kazna>();
            this.Optuzenik = new HashSet<Optuzenik>();
            this.Ostecenik = new HashSet<Ostecenik>();
            this.Sudionik = new HashSet<Sudionik>();
        }
    
        public int IDOsobe { get; set; }
        public string OIB { get; set; }
        public string UlicaIKucniBr { get; set; }
        public Nullable<int> PBr { get; set; }
    
        public virtual FizickaOsoba FizickaOsoba { get; set; }
        public virtual ICollection<Kazna> Kazna { get; set; }
        public virtual Mjesto Mjesto { get; set; }
        public virtual ICollection<Optuzenik> Optuzenik { get; set; }
        public virtual ICollection<Ostecenik> Ostecenik { get; set; }
        public virtual PravnaOsoba PravnaOsoba { get; set; }
        public virtual ICollection<Sudionik> Sudionik { get; set; }
    }
}
