//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RPPP
{
    using System;
    using System.Collections.Generic;
    
    public partial class Proces
    {
        public Proces()
        {
            this.Optuzenik = new HashSet<Optuzenik>();
            this.Ostecenik = new HashSet<Ostecenik>();
            this.Rociste = new HashSet<Rociste>();
            this.StavkaSpisa = new HashSet<StavkaSpisa>();
            this.SudskoVijece = new HashSet<SudskoVijece>();
            this.Svjedok = new HashSet<Svjedok>();
            this.Tuzitelj = new HashSet<Tuzitelj>();
        }
    
        public int IDProcesa { get; set; }
        public int Broj { get; set; }
        public string Klasa { get; set; }
        public string Oznaka { get; set; }
        public byte[] Optuznica { get; set; }
        public Nullable<int> Sud { get; set; }
    
        public virtual ICollection<Optuzenik> Optuzenik { get; set; }
        public virtual ICollection<Ostecenik> Ostecenik { get; set; }
        public virtual Sud Sud1 { get; set; }
        public virtual ICollection<Rociste> Rociste { get; set; }
        public virtual ICollection<StavkaSpisa> StavkaSpisa { get; set; }
        public virtual ICollection<SudskoVijece> SudskoVijece { get; set; }
        public virtual ICollection<Svjedok> Svjedok { get; set; }
        public virtual ICollection<Tuzitelj> Tuzitelj { get; set; }
    }
}
