//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RPPP
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sud
    {
        public Sud()
        {
            this.Proces = new HashSet<Proces>();
            this.Sud1 = new HashSet<Sud>();
        }
    
        public int IDSuda { get; set; }
        public string Naziv { get; set; }
        public string UlicaIKucniBr { get; set; }
        public Nullable<int> PBr { get; set; }
        public Nullable<int> Kategorija { get; set; }
        public Nullable<int> Nadredeni { get; set; }
    
        public virtual KategorijaSuda KategorijaSuda { get; set; }
        public virtual Mjesto Mjesto { get; set; }
        public virtual ICollection<Proces> Proces { get; set; }
        public virtual ICollection<Sud> Sud1 { get; set; }
        public virtual Sud Sud2 { get; set; }
    }
}
