//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RPPP
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sudionik
    {
        public int IDSudionika { get; set; }
        public Nullable<int> IDOsobe { get; set; }
        public Nullable<int> IDRocista { get; set; }
        public Nullable<int> Uloga { get; set; }
    
        public virtual Osoba Osoba { get; set; }
        public virtual Rociste Rociste { get; set; }
        public virtual UlogaSudionika UlogaSudionika { get; set; }
    }
}
