//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RPPP
{
    using System;
    using System.Collections.Generic;
    
    public partial class UlogaSudionika
    {
        public UlogaSudionika()
        {
            this.Sudionik = new HashSet<Sudionik>();
        }
    
        public int SifraUloge { get; set; }
        public string NazivUloge { get; set; }
    
        public virtual ICollection<Sudionik> Sudionik { get; set; }
    }
}
